### ISSUE TITLE
Allow run name to be none when computing cost of a run

### ISSUE THREAD

**Issue by smlchen** [aws-samples/amazon-omics-tutorials#46]
`compute_pricing.py` fails with the following error if run name is empty.
```
python compute_pricing.py 9427547
Traceback (most recent call last):
  File "/Users/sachen/Desktop/amazon-omics-tutorials/utils/scripts/compute_pricing.py", line 147, in <module>
    cost = get_run_cost(args.run_id, client=session.client('omics'), offering=args.offering)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sachen/Desktop/amazon-omics-tutorials/utils/scripts/compute_pricing.py", line 126, in get_run_cost
    "name": run['name'],
            ~~~^^^^^^^^
KeyError: 'name'
```

**Comment by wleepang** [comment]
Resolved in #47
