### ISSUE TITLE
Error while using compute_pricing.py

### ISSUE THREAD

**Issue by nbulsara** [aws-samples/amazon-omics-tutorials#49]
Recent usage of the compute_pricing.py script leads to an error as follows:

Traceback (most recent call last):
  File "/Users/nbulsara/Documents/code/amazon-omics-tutorials/utils/scripts/compute_pricing.py", line 147, in <module>
    cost = get_run_cost(args.run_id, client=session.client('omics'), offering=args.offering)
  File "/Users/nbulsara/Documents/code/amazon-omics-tutorials/utils/scripts/compute_pricing.py", line 96, in get_run_cost
    usd_per_hour = float(pricing[task['instanceType']]['priceDimensions']['pricePerUnit']['USD'])
KeyError: 'instanceType'

Steps to reproduce:

python3 compute_pricing.py <RUN_ID> --profile <AWS_PROFILE> --region <AWS-REGION>

**Comment by wleepang** [comment]
Can you check your `boto3` version and update as needed?

**Comment by Tmacphee13** [comment]
Hi @wleepang, that did the trick! Thanks both for the help

**Comment by wleepang** [comment]
No problem! Let us know if you have any more issues.
